spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace